version: "3.3"
services:
  
  receiver:
    build:
      context: test/mocks
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command:
      - --app
      - app:app
      - run
      - --host
      - "0.0.0.0"
      - --port
      - "8080"
