name: main Merges
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
  id-token: write
  packages: write
jobs:
  containerize:
    uses: ./.github/workflows/build.yaml
    with:
      publish: true
